#!/usr/bin/env bash
# i forgot to write another comment
counter=1
while [ $counter -lt 21 ]
do
	case $counter in
		4)
			echo $counter
			echo "bad luck from China"
			;;
		9)
			echo $counter
			echo "bad luck from Japan"
			;;
		17)
			echo $counter
			echo "bad luck from Italy"
			;;
		*)
			echo $counter
			;;
	esac
	let counter+=1
done
