#!/usr/bin/env bash
# i forgot to write another comment
counter=1
while [ $counter -le 20 ]; do
	case $counter in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck Form Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac
	((counter++))
done
