#!/usr/bin/env bash
# i forgot to write another comment
counter=1
while [ $counter -le 20 ]; do
	if [$counter -eq 4 ]; then 
		echo "bad luck from China"
	elif [ $counter -eq 9 ]; then
		echo "bad luck from Japan"
	elif [ $counter -eq 17 ]; then
		echo "bad luck from Italy"
	fi
	((counter++))
done
