#!/usr/bin/env bash
#using a nested loop to display the time 
hour=0
minute=1
while true; do 
	echo "Time: $(printf "%02d;%02d" $hour $minute)"
	minute=$((minute % 60 + 1))
	if [[ $minute -eq 60 ]]; then
		minute =1
	fi
	hour=$((hour % 12 + 1))
	sleep 1
done

