#!/usr/bin/env bash
#using a nested loop to display the time
HOURS=0
while [ $HOURS -lt 13 ]
do 
	echo "Hour: $HOURS"
	MINUTES=1
	while [ $MINUTES -lt 60 ] 
	do 
		echo $MINUTES
		let  MINUTES+=1
	done 
	((HOURS+=1))
done
