#!/usr/bin/env bash
#i probably need a comment on this
filename="school"
if [ -f "$filename" ]; then 
	echo "school file exist"
	if [! -s "$filename" ]; then 
		echo "school file is empty"
	else 
		echo "school file is not empty"
		if [ -e "$filename" ] && [! -L "$filename" ]; then 
			echo "school is a regular file"
		fi
	fi
else
	echo "school file does not exist"
fi
